name: alignspace
services:
  - name: frontend
    source_dir: as-ai-web
    dockerfile_path: as-ai-web/Dockerfile
    http_port: 80
    health_check:
      http_path: /

  - name: backend
    source_dir: as-ai-server
    dockerfile_path: as-ai-server/Dockerfile
    http_port: 8000
    health_check:
      http_path: /health   # make sure your backend has this route
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${{ DATABASE_URL }}